require("ItemTweaker_Copy_CC");

--Firearms B41
--Firearms
TweakItem("Base.FN_FAL","DisplayCategory","WepFire");
TweakItem("Base.M16A2","DisplayCategory","WepFire");
TweakItem("Base.AR15","DisplayCategory","WepFire");
TweakItem("Base.M60","DisplayCategory","WepFire");
TweakItem("Base.AK47","DisplayCategory","WepFire");
TweakItem("Base.Glock17","DisplayCategory","WepFire");
TweakItem("Base.Winchester94","DisplayCategory","WepFire");
TweakItem("Base.Winchester73","DisplayCategory","WepFire");
TweakItem("Base.ColtPeacemaker","DisplayCategory","WepFire");
TweakItem("Base.HuntingRifle_Sawn","DisplayCategory","WepFire");
TweakItem("Base.Rugerm7722","DisplayCategory","WepFire");
TweakItem("Base.SKS","DisplayCategory","WepFire");
TweakItem("Base.M24Rifle","DisplayCategory","WepFire");
TweakItem("Base.Mossberg500","DisplayCategory","WepFire");
TweakItem("Base.Mossberg500Tactical","DisplayCategory","WepFire");
TweakItem("Base.Remington870Wood","DisplayCategory","WepFire");
TweakItem("Base.Remington870Sawnoff","DisplayCategory","WepFire");
TweakItem("Base.M37","DisplayCategory","WepFire");
TweakItem("Base.M37Sawnoff","DisplayCategory","WepFire");
TweakItem("Base.MP5","DisplayCategory","WepFire");
TweakItem("Base.UZI","DisplayCategory","WepFire");
TweakItem("Base.Mac10","DisplayCategory","WepFire");
--Magazines
TweakItem("Base.Glock17Mag","DisplayCategory","WepAmmoMag");
TweakItem("Base.MP5Mag","DisplayCategory","WepAmmoMag");
TweakItem("Base.UZIMag","DisplayCategory","WepAmmoMag");
TweakItem("Base.Mac10Mag","DisplayCategory","WepAmmoMag");
TweakItem("Base.AK_Mag","DisplayCategory","WepAmmoMag");
TweakItem("Base.M60Mag","DisplayCategory","WepAmmoMag");
TweakItem("Base.FN_FAL_Mag","DisplayCategory","WepAmmoMag");
--Ammo
TweakItem("Base.Bullets4440","DisplayCategory","Ammo");
TweakItem("Base.Bullets4440Box","DisplayCategory","Ammo");
TweakItem("Base.762x51Bullets","DisplayCategory","Ammo");
TweakItem("Base.762x51Box","DisplayCategory","Ammo");
TweakItem("Base.762x39Bullets","DisplayCategory","Ammo");
TweakItem("Base.762x39Box","DisplayCategory","Ammo");
TweakItem("Base.Bullets22","DisplayCategory","Ammo");
TweakItem("Base.Bullets22Box","DisplayCategory","Ammo");
--WeaponPart
TweakItem("Base.45Silencer","DisplayCategory","WepPart");
TweakItem("Base.9mmSilencer","DisplayCategory","WepPart");
TweakItem("Base.223Silencer","DisplayCategory","WepPart");
TweakItem("Base.308Silencer","DisplayCategory","WepPart");
TweakItem("Base.ImprovisedSilencer","DisplayCategory","WepPart");
TweakItem("Base.Silencer_PopBottle","DisplayCategory","WepPart");
TweakItem("Base.9mmCompensator","DisplayCategory","WepPart");
TweakItem("Base.GunLightImprovised","DisplayCategory","WepPart");
TweakItem("Base.ExtendedRecoilPad","DisplayCategory","WepPart");
TweakItem("Base.Rifle_Bipod","DisplayCategory","WepPart");
TweakItem("Base.AmmoStock","DisplayCategory","WepPart");
TweakItem("Base.TacticalStock","DisplayCategory","WepPart");
TweakItem("Base.ShotgunStock","DisplayCategory","WepPart");
TweakItem("Base.LightShotgunStock","DisplayCategory","WepPart");
TweakItem("Base.MP5_Stock_Extended","DisplayCategory","WepPart");
TweakItem("Base.MP5_Stock_Detracted","DisplayCategory","WepPart");
TweakItem("Base.UZI_Stock_Extended","DisplayCategory","WepPart");
TweakItem("Base.UZI_Stock_Detracted","DisplayCategory","WepPart");
TweakItem("Base.Mac10_Stock_Extended","DisplayCategory","WepPart");
TweakItem("Base.Mac10_Stock_Detracted","DisplayCategory","WepPart");
TweakItem("Base.Sling_Leather","DisplayCategory","WepPart");
TweakItem("Base.Sling_Olive","DisplayCategory","WepPart");
TweakItem("Base.Sling_Camo","DisplayCategory","WepPart");
TweakItem("Base.x4-x12Scope","DisplayCategory","WepPart");
--AmmoCans
TweakItem("Base.AmmoCan762","DisplayCategory","Container");
TweakItem("Base.AmmoCan762x39","DisplayCategory","Container");
TweakItem("Base.AmmoCan556","DisplayCategory","Container");
TweakItem("Base.AmmoCan223","DisplayCategory","Container");
TweakItem("Base.AmmoCan308","DisplayCategory","Container");
TweakItem("Base.AmmoCan9mm","DisplayCategory","Container");
--Broken
TweakItem("Base.ImprovisedSilencer_Broken","DisplayCategory","Junk");
TweakItem("Base.Silencer_PopBottle_Broken","DisplayCategory","Junk");
